services:
  mongodb:
    image: mongo:latest
    container_name: notes-mongodb
    environment:
      - MONGO_INITDB_DATABASE=notesdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: notes-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/notesdb
    depends_on:
      - mongodb

volumes:
  mongodb_data: