spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notesdb
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC

server:
  port: 8080

logging:
  level:
    com.yevbes.notesapp: DEBUG