spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notesdb
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

logging:
  level:
    com.yevbes.notesapp: DEBUG